name = "CLEARSWI"
uuid = "06ae4d9b-ce5e-4813-a1b3-426e46312ec2"
authors = ["Korbinian Eckstein"]
version = "0.3.0"

[deps]
MriResearchTools = "557dad86-b9bd-4533-8525-1a39684d020f"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
MriResearchTools = "0.6"
Requires = "1"
julia = "1.5"
