name = "CLEARSWI"
uuid = "06ae4d9b-ce5e-4813-a1b3-426e46312ec2"
authors = ["Korbinian Eckstein"]
version = "1.0.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
MriResearchTools = "557dad86-b9bd-4533-8525-1a39684d020f"
QSM = "794fc106-2fa4-440f-961c-0d7d7b47016a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"


[weakdeps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"

[extensions]
ClearswiApp = "ArgParse"

[compat]
ArgParse = "1"
MriResearchTools = "3.0"
julia = "1.5"
